#!/bin/sh
# Gradle start-up script (POSIX). Wrapper JAR may be generated by Android Studio Sync
# if missing — see gradle/wrapper/gradle-wrapper.properties.

##############################################################################
# Attempt to set APP_HOME
##############################################################################
app_path=$0
while [ -h "$app_path" ]; do
  ls=$(ls -ld "$app_path")
  link=${ls#*' -> '}
  case $link in
    /*) app_path=$link ;;
    *) app_path=$(dirname "$app_path")/$link ;;
  esac
done
APP_HOME=$(cd "$(dirname "$app_path")" && pwd -P) || exit
APP_NAME="Gradle"
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ ! -f "$CLASSPATH" ]; then
  echo "gradle-wrapper.jar missing."
  echo "Open this project in Android Studio (File → Open) to generate the wrapper,"
  echo "or run: gradle wrapper --gradle-version 8.7"
  exit 1
fi

if [ -n "$JAVA_HOME" ]; then
  JAVACMD=$JAVA_HOME/bin/java
else
  JAVACMD=java
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
